default:
  image: nixos/nix:2.18.0
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.confbash-5.2# nix flake

notebooks:
  stage: build
  script:
    - nix build .#notebooks
  artifacts:
    paths:
      - ./result/generated/
