default:
  image: nixos/nix:2.18.0
  before_script:
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

notebooks:
  stage: Build
  script:
    - nix build .#notebooks
  artifacts:
    paths:
      - ./result/generated/
